### ISSUE TITLE
hi exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by beibeii** [vinhkhuc/JFastText#13]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.github.jfasttext.JFastText.predictProba(JFastText.java:60)

**Comment by IT-Glory** [comment]
Have you solved the problem？

**Comment by chenjun0210** [comment]
Have you solved the problem？

**Comment by sandove** [comment]
Came across the same problem. Could anyone help with this?

**Comment by shayts7** [comment]
+1

**Comment by sandove** [comment]
Finally I use this instead:  [https://github.com/ivanhk/fastText_java](url)

**Comment by lidalei** [comment]
Could you release the code that caused the problem. I tried predictProba and it works fine.

**Comment by enochmonightsky** [comment]
this problem come to me too,and i can't find the source code,is there any one can help?thank you very much.

**Comment by enochmonightsky** [comment]
i wonder what is the rule of the text to be predict,i test text,text+"\t"+text,text+"\n"+text,etc,all of them come to index out of bounds.
