### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by wangzhe258369** [vinhkhuc/JFastText#17]
Get this exception when load model:
`Exception in thread "main" java.lang.RuntimeException: vector<T> too long
	at com.github.jfasttext.FastTextWrapper$FastTextApi.loadModel(Native Method)
	at com.github.jfasttext.JFastText.loadModel(JFastText.java:25)`
How to fix this?

**Comment by nedved1990** [comment]
+1

**Comment by nedved1990** [comment]
@vinhkhuc Could you please help us to solve this problem?
